spring:
  application:
    name: conversor-moedas
  datasource:
    url: jdbc:postgresql://localhost:5432/conversor
    username: cidadania4u-ecossistema
    password: cidadania4u-ecossistema
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    out-of-order: true
    clean-disabled: true
    validate-on-migrate: true

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub